### ISSUE TITLE
Printable roster with space for TDs, CAS, COMP and MNG

### ISSUE THREAD

**Issue by Rangor** [wrightomated/blood-bowl-roster#66]
Really love this tool, just great for trying out builds and in general playing with Blood Bowl.

One very nice feature for me personally would be spaces for "match notes" that can be used during play like TDs, CAS, COMP and MNG. This could be just for the printed version or it's own print version.

Thanks again for a great tool

**Comment by Rangor** [comment]
The MNG field is already there I se now

**Comment by wrightomated** [comment]
Hey Rangor thanks for the feedback!

Definitely sounds like an easy addition. How do you envisage it?  A row below each player?

**Comment by Rangor** [comment]
I actually made a tweaked version with some very small changes here:
https://bbteam.herokuapp.com/
(only made this for mye personal use btw)
The changes made here are hacky and bad, but I just wanted to test adding lines to the table, three columns for TDs, CAS and COMP before the SPP field and I also removed the "Hiring fee" column.
The idea was that these tweaks would only show in the "print" version but I'm terrible at web so I just did it like this to try it.

So something like that was my idea but I think the best solution would be if they only appeared on the print verison, maybe?

**Comment by wrightomated** [comment]
Ah nice one!

"only made this for my personal use btw" Feel free to do whatever you want! It's open source 😃 

"The changes made here are hacky and bad" Haha definitely not. I didn't really make this project easy to edit, it is all a bit hacky. I was testing out Svelte with no planning and needed an idea to build out. I decided to release it because why not.

I like this idea of having different columns for printing. What about having an options box where the user can choose which columns are visible? Could even have the option for adding custom columns.

**Comment by Rangor** [comment]
Choosing what columns are visible for printing and also custom columns sounds perfect 🙂

**Comment by wrightomated** [comment]
Hey Rangor,

I've added some column editing functionality (the cog icon above the table).
![image](https://user-images.githubusercontent.com/33916051/149651780-42d8377f-cdcb-470b-8e32-3f7afc847970.png)

I hope to build it out a more but its adds some functionality.
